---
- name: install epel-release
  dnf:
    name:
      - epel-release
    state: present

- name: install s3fs
  dnf:
    name:
      - s3fs-fuse
    state: present

- name: create dir
  file:
    path: /s3
    state: directory

- name: s3 passwd
  template:
    src: templates/passwd-s3fs.j2
    dest: ~/.passwd-s3fs
    mode: 0600

- name: mount
  mount:
    src: "s3fs#{{ bucket_name }}"
    name: /s3
    fstype: fuse
    opts: "_netdev,allow_other,use_path_request_style,url=https://s3.timeweb.com,passwd_file=/root/.passwd-s3fs"
    state: mounted
