---
- name: install epel-release
  dnf:
    name:
      - epel-release
    state: present

- name: install s3fs
  dnf:
    name:
      - s3fs-fuse
    state: present

- name: create dir
  file:
    path: /s3
    state: directory

- name: s3 passwd
  template:
    src: templates/passwd-s3fs.j2
    dest: ~/.passwd-s3fs
